### ISSUE TITLE
data mapping

### ISSUE THREAD

**Issue by philippe-brunier-cas** [philippe-brunier-cas/metalm#1]
rifo data mapping

- rivedere la colonna delle unità di misura
- aggiugnere colonna data types, fai riferimento a https://pbpython.com/pandas_dtypes.html
- fare il mapping mancante

**Comment by riccardo-tolosano-cogne** [comment]
aggiunte le modifiche agli header e modificato il markdown per mostrare la tabella delle colonne per il file degli ossidi

**Comment by philippe-brunier-cas** [comment]
Ciao,
scusa ma mi sono spiegato male.

Il file che dovevi mappare era analisi_metallografiche e non quelli già presenti nel data preparation. 

Domani ti spiego bene.
